"""add_access_campaigns

Revision ID: ccee45bac0f5
Revises: 0ea4fb7eaba4
Create Date: 2026-08-06 18:29:30.705881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ccee45bac0f5'
down_revision: Union[str, Sequence[str], None] = '0ea4fb7eaba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_name', sa.String(length=100), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('duration_hours', sa.Integer(), nullable=False),
    sa.Column('max_redemptions', sa.Integer(), nullable=False),
    sa.Column('redeemed_count', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['platform.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    schema='billing'
    )
    op.create_index('idx_campaigns_token', 'access_campaigns', ['token'], unique=True, schema='billing')
    op.create_table('campaign_redemptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('access_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['billing.access_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['platform.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'user_id', name='uq_campaign_user_redemption'),
    schema='billing'
    )
    op.create_index('idx_redemptions_campaign', 'campaign_redemptions', ['campaign_id'], unique=False, schema='billing')
    op.create_index('idx_redemptions_user', 'campaign_redemptions', ['user_id'], unique=False, schema='billing')
    op.drop_table('prediction_feedback')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediction_feedback',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tab', sa.TEXT(), server_default=sa.text("'general'::text"), autoincrement=False, nullable=False),
    sa.Column('user_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ai_response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('birth_details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('prediction_feedback_pkey'))
    )
    op.drop_index('idx_redemptions_user', table_name='campaign_redemptions', schema='billing')
    op.drop_index('idx_redemptions_campaign', table_name='campaign_redemptions', schema='billing')
    op.drop_table('campaign_redemptions', schema='billing')
    op.drop_index('idx_campaigns_token', table_name='access_campaigns', schema='billing')
    op.drop_table('access_campaigns', schema='billing')
    # ### end Alembic commands ###
